import { NextResponse } from 'next/server';

export async function GET() {
  const registryData = {
    version: "0.1.0",
    updatedAt: new Date().toISOString(),
    blocks: [
      {
        id: "auth-login",
        name: "Auth — Login",
        description: "A clean, full-page authentication layout with email/password form, social login slots, and subtle Framer Motion animations.",
        tier: "basic",
        version: "1.0.0",
        license: "MIT",
        files: [
          { path: "auth-login/index.tsx",                    url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/auth-login/index.tsx" },
          { path: "auth-login/components/LoginForm.tsx",     url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/auth-login/components/LoginForm.tsx" },
          { path: "auth-login/components/OAuthButtons.tsx",  url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/auth-login/components/OAuthButtons.tsx" },
          { path: "auth-login/block.json",                   url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/auth-login/block.json" },
        ],
        dependencies: ["framer-motion", "lucide-react"],
        devDependencies: [],
        requiresTailwind: true,
        requiresGwenTheme: true,
      },
      {
        id: "parallax-hero",
        name: "Parallax Hero",
        description: "A cinematic parallax hero section with depth layers, mouse-tracking 3D tilt, and scroll-driven animations.",
        tier: "supreme",
        version: "1.0.0",
        license: "BSL-1.1",
        files: [
          { path: "parallax-hero/index.tsx",                          url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/parallax-hero/index.tsx" },
          { path: "parallax-hero/components/FloatingImage.tsx",       url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/parallax-hero/components/FloatingImage.tsx" },
          { path: "parallax-hero/components/TextHoverEffect.tsx",     url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/parallax-hero/components/TextHoverEffect.tsx" },
          { path: "parallax-hero/block.json",                         url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/parallax-hero/block.json" },
        ],
        dependencies: ["framer-motion"],
        devDependencies: [],
        requiresTailwind: true,
        requiresGwenTheme: true,
      },
      {
        id: "ai-chat-hero",
        name: "AI Chat Hero",
        description: "Full-page AI chat interface hero block, Gemini-inspired with GwenUI dark tokens.",
        tier: "basic",
        version: "1.0.0",
        license: "MIT",
        files: [
          { path: "ai-chat-hero/index.tsx",                          url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/ai-chat-hero/index.tsx" },
          { path: "ai-chat-hero/components/ChatSidebar.tsx",         url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/ai-chat-hero/components/ChatSidebar.tsx" },
          { path: "ai-chat-hero/components/ChatInput.tsx",           url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/ai-chat-hero/components/ChatInput.tsx" },
          { path: "ai-chat-hero/components/SuggestionChips.tsx",     url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/ai-chat-hero/components/SuggestionChips.tsx" },
          { path: "ai-chat-hero/hooks/useChatInput.ts",              url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/ai-chat-hero/hooks/useChatInput.ts" },
          { path: "ai-chat-hero/block.json",                         url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/ai-chat-hero/block.json" },
        ],
        dependencies: ["framer-motion", "lucide-react"],
        devDependencies: [],
        requiresTailwind: true,
        requiresGwenTheme: true,
      },
      {
        id: "dynamic-pricing",
        name: "Dynamic Pricing",
        description: "Dynamic Pricing block component with slot-machine digit animation.",
        tier: "basic",
        version: "1.0.0",
        license: "MIT",
        files: [
          { path: "dynamic-pricing/dynamic-pricing.tsx",  url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/dynamic-pricing/dynamic-pricing.tsx" },
          { path: "dynamic-pricing/index.ts",             url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/dynamic-pricing/index.ts" },
          { path: "dynamic-pricing/block.json",           url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/dynamic-pricing/block.json" },
        ],
        dependencies: ["framer-motion", "lucide-react"],
        devDependencies: [],
        requiresTailwind: true,
        requiresGwenTheme: true,
      },
      {
        id: "meet-the-team",
        name: "Meet the Team",
        description: "Editorial Meet the Team block with playing-card style member profiles and photo overflow animations.",
        tier: "basic",
        version: "1.0.0",
        license: "MIT",
        files: [
          { path: "meet-the-team/meet-the-team.tsx",  url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/meet-the-team/meet-the-team.tsx" },
          { path: "meet-the-team/index.ts",           url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/meet-the-team/index.ts" },
          { path: "meet-the-team/block.json",         url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/meet-the-team/block.json" },
        ],
        dependencies: ["framer-motion", "lucide-react"],
        devDependencies: [],
        requiresTailwind: true,
        requiresGwenTheme: true,
      },
      {
        id: "before-after-slider",
        name: "Before-After Slider",
        description: "Touch-friendly image comparison slider with elastic spring physics and stretch effects.",
        tier: "basic",
        version: "1.0.0",
        license: "MIT",
        files: [
          { path: "before-after-slider/before-after-slider.tsx",  url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/before-after-slider/before-after-slider.tsx" },
          { path: "before-after-slider/index.ts",                 url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/before-after-slider/index.ts" },
          { path: "before-after-slider/block.json",               url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/before-after-slider/block.json" },
        ],
        dependencies: ["framer-motion", "lucide-react"],
        devDependencies: [],
        requiresTailwind: true,
        requiresGwenTheme: false,
      },
      {
        id: "testimonial-marquee",
        name: "Testimonial Marquee",
        description: "Infinite auto-scroll testimonial marquee with Twitter/X style cards and dual-row opposite-direction layout.",
        tier: "basic",
        version: "1.0.0",
        license: "MIT",
        files: [
          { path: "testimonial-marquee/index.tsx",                          url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/testimonial-marquee/index.tsx" },
          { path: "testimonial-marquee/components/TestimonialCard.tsx",     url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/testimonial-marquee/components/TestimonialCard.tsx" },
          { path: "testimonial-marquee/components/MarqueeRow.tsx",          url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/testimonial-marquee/components/MarqueeRow.tsx" },
          { path: "testimonial-marquee/block.json",                         url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/testimonial-marquee/block.json" },
        ],
        dependencies: ["framer-motion", "lucide-react"],
        devDependencies: [],
        requiresTailwind: true,
        requiresGwenTheme: false,
      },
      {
        id: "bento-grid",
        name: "Bento Grid",
        description: "Asymmetric CSS grid layout with staggered entrance animations and hover depth effects.",
        tier: "basic",
        version: "1.0.0",
        license: "MIT",
        files: [
          { path: "bento-grid/BentoGrid.tsx",  url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/bento-grid/BentoGrid.tsx" },
          { path: "bento-grid/index.ts",       url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/bento-grid/index.ts" },
          { path: "bento-grid/block.json",     url: "https://raw.githubusercontent.com/jinxsuper/gwenui/main/blocks/bento-grid/block.json" },
        ],
        dependencies: ["framer-motion", "lucide-react"],
        devDependencies: [],
        requiresTailwind: true,
        requiresGwenTheme: false,
      },
    ],
  };

  return NextResponse.json(registryData, {
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=86400',
    },
  });
}
